common/models/UsersAddress.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "tbl_users_address".
 *
 * @property integer $id
 * @property integer $id_user
 * @property string $description
 * @property integer $id_region
 * @property integer $id_city
 * @property integer $id_street
 * @property integer $id_area
 * @property string $house
 * @property integer $apartment
 * @property integer $is_map
 * description
 *
 * @property TblUsers $idUser
 * @property TblUsersAddressRegion $idRegion
 * @property TblUsersAddressCity $idCity
 * @property TblUsersAddressStreet $idStreet
 * @property TblUsersAddressArea $idArea
 */
class UsersAddress extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_users_address';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_user', 'id_region', 'id_city', 'id_street', 'id_area', 'apartment', 'is_map'], 'integer'],
            [['house'], 'string', 'max' => 10],
            [['description'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Пользователь',
            'description' => "Описание",
            'id_region' => 'Регион',
            'id_city' => 'Город',
            'id_street' => 'Улица',
            'id_area' => 'Район',
            'house' => 'Дом',
            'apartment' => 'Офис',
            'is_map' => 'Показывать на карте',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'id_user']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegion()
    {
        return $this->hasOne(UsersAddressRegion::className(), ['id' => 'id_region']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCity()
    {
        return $this->hasOne(UsersAddressCity::className(), ['id' => 'id_city']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStreet()
    {
        return $this->hasOne(UsersAddressStreet::className(), ['id' => 'id_street']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArea()
    {
        return $this->hasOne(UsersAddressArea::className(), ['id' => 'id_area']);
    }

    public function getText()
    {
        $text = '';
        if($this->description)
            $text .= $this->description.": ";
        else
            $text .= "Адрес: ";
        $text .= $this->region->title.', г.'.$this->city->title.", ул.".$this->street->title.", ";
        $text .= "д. ".$this->house.", ";
        if( $this->apartment!="" )
            $text .= "оф. ".$this->apartment." ";
        $text .=" (".$this->area->title.") ";
        return $text;
    }

    public function getGeoText()
    {
        $text = '';
        $text .= $this->region->title.', '.$this->city->title.", ".$this->street->title." ".$this->house;
        return $text;
    }
}

common/models/UsersPhones.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "tbl_users_phones".
 *
 * @property integer $id
 * @property integer $id_user
 * @property integer $id_code
 * @property string $phone
 * @property string $title
 *
 * @property TblUsersProfile $idUser
 */
class UsersPhones extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_users_phones';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_user'], 'required'],
            [['id_user', 'id_code'], 'integer'],
            [['phone'], 'string', 'max' => 45],
            [['title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'id_code' => 'Код',
            'phone' => 'Тел',
            'title' => 'Название',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(UsersProfile::className(), ['id' => 'id_user']);
    }

    public function getCode()
    {
        return $this->hasOne(CodesPhones::className(), ['id' => 'id_code']);
    }

    public function getText()
    {
        $text = '';
        if($this->title)
            $text .= $this->title.": ";
        else
            $text .= "Телефон: ";
        $text .= $this->code->title;
        $text .= " ".$this->phone." ";
        return $text;
    }
}

common/models/UsersProfile.php
<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;
/**
 * This is the model class for table "tbl_users_profile".
 *
 * @property integer $id
 * @property integer $id_user
 * @property integer $id_status
 * @property string $title
 * @property string $image
 * @property double $balance
 * @property integer $bonus
 * @property string $url_vk
 * @property string $url_www
 * @property string $schedule
 *
 * @property TblUsersDonate[] $tblUsersDonates
 * @property TblUsersPhones[] $tblUsersPhones
 * @property TblUsers $idUser
 * @property TblUsersRating[] $tblUsersRatings
 */
class UsersProfile extends \yii\db\ActiveRecord
{
    public $_image;
    public $_deleteimage;

    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_users_profile';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_user'], 'required'],
            [['id_user', 'id_status', 'bonus'], 'integer'],
            [['balance'], 'number'],
            [['schedule'], 'safe'],
            [['title'], 'string', 'max' => 128],
            [['image'], 'string', 'max' => 255],
            [['url_vk', 'url_www'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Пользователь',
            'id_status' => 'Статус',
            'title' => 'Заголовок',
            '_image' => 'Изображение',
            'balance' => 'Баланс',
            'bonus' => 'Бонус',
            'url_vk' => 'Ссылка вконтакте',
            'url_www' => 'Ссылка личный сайт',
            'schedule' => 'Время работы',
            '_deleteimage' => 'Удалить изображение'
        ];
    }

    public function getTypeOrganization()
    {
        return $this->hasOne(TypeOrganization::className(), ['id' => 'id_type']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsersDonates()
    {
        return $this->hasMany(UsersDonate::className(), ['id_user' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'id_user']);
    }

     public function getStatus()
    {
        return $this->hasOne(UsersStatus::className(), ['id' => 'id_status']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsersRatings()
    {
        return $this->hasMany(UsersRating::className(), ['id_user' => 'id']);
    }

    public function beforeDelete()
    {
        if (parent::beforeDelete()) {
            $this->removeImages();
            $this->clearImagesCache();
            return true;
        } else {
            return false;
        }
    }

     public function afterSave($insert, $values)
    {
         $this->_image = UploadedFile::getInstance($this, '_image');
        if($this->_image !== null && $this->_image->tempName !== '' && $this->_image instanceof UploadedFile) { // проверяем есть ли загруженное изображение
            if (!$this->isNewRecord){
                $this->removeImages(); // удаляем старое изображение 
            }
            $this->attachImage($this->_image->tempName);
            $this->clearImagesCache();
            $this->_image->reset();
        }
        if( $this->_deleteimage )
        {
            $this->removeImages();
            $this->clearImagesCache();
        }

        if (parent::afterSave($insert, $values)) {
            return true;
        } else {
            return false;
        }
    }

}

common/models/UsersViews.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "tbl_users_views".
 *
 * @property integer $id
 * @property integer $id_user
 * @property string $created
 *
 * @property TblUsers $idUser
 */
class UsersViews extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_users_views';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_user', 'created'], 'required'],
            [['id_user'], 'integer'],
            [['created'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'created' => 'Created',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUser()
    {
        return $this->hasOne(TblUsers::className(), ['id' => 'id_user']);
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\User;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'create', 'update', 'delete'],
                'rules' => [
                    // deny all POST requests
                    [
                        'allow' => true,
                        'verbs' => ['POST']
                    ],
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Users;
use common\models\UsersProfile;
use common\models\UsersAddress;
use common\models\search\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'create', 'update', 'delete'],
                'rules' => [
                    // deny all POST requests
                    [
                        'allow' => true,
                        'verbs' => ['POST']
                    ],
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
         
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $model = new Users;
        $usersProfileModel = new UsersProfile;
        $usersAddressModel = new UsersAddress;
        if (Yii::$app->request->post()) {
            $model->load(Yii::$app->request->post());
            if($model->save()) {
                $usersProfileModel->id_user = $model->id;
                $usersAddressModel->id_user = $model->id;
                if($usersProfileModel->save() && $usersAddressModel->save()) {
                    Yii::$app->session->setFlash('flashMessage', array('success', 'Новая запись добавлена.'));
                    return $this->redirect(['/users-profile/update', 'id' => $usersProfileModel->id]);
                }
            }

                
        } else {
             
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('flashMessage', array('success', 'Запись успешно обновлена.'));
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
             
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash('flashMessage', array('success', 'Запись успешно удалена.'));
        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/users/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\Users $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'uid')->textInput(['maxlength' => 45]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'new_password')->passwordInput(['maxlength' => 255]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\search\UsersSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'uid') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'created') ?>

    <?php // echo $form->field($model, 'updated') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/users/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Users $model
 */

$this->title = 'Добавить пользователя';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/users/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\Alert;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\UsersSearch $searchModel
 */

$this->title = 'Организации';
$this->params['breadcrumbs'][] = $this->title;

?>
<h2>Список организаций</h2>
<div class="organizations">
    <div class="col50">
        <div class="group">
            <?php $centerok = false;?>
            <?php foreach ($data as $key => $value):?>
                    <?php if($key == 0):?>
                        <div class="char"><?= mb_substr($value->title,0,1,'utf-8');?></div>
                    <?php else:
                        if( mb_substr($data[$key-1]->title,0,1,'utf-8') != mb_substr($value->title,0,1,'utf-8')):?>
                            </div>
                            <?php if($key >= count($data)/2 && !$centerok):?>
                                </div>
                                <div class="col50">
                                <?php $centerok=true;?>
                            <?php endif;?>
                            <div class="group">
                            <div class="char"><?= mb_substr($value->title,0,1,'utf-8');?></div>
                        <?php endif;
                    endif;?>
                    <div class="item">
                        <a href="/users/<?=$value->user->id?>"><?=$value->title?></a>
                    </div>
            <?php endforeach;?>
        </div>
    </div>
    <div class="clear"></div>
</div>

frontend/views/users/update.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Alert;

/**
 * @var yii\web\View $this
 * @var app\models\Users $model
 */

$this->title = 'Редактировать пользователя: ' . $model->uid;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->uid];
$this->params['breadcrumbs'][] = 'Редактировать';

if(Yii::$app->session->hasFlash('flashMessage')):
    echo Alert::widget([
    'options' => [
        'class' => 'alert-'.Yii::$app->session->getFlash('flashMessage')[0],
        ],
        'body' => Yii::$app->session->getFlash('flashMessage')[1],
    ]);
endif;
?>
<div class="users-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/users/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/**
 * @var yii\web\View $this
 * @var app\models\Users $model
 */

$this->title = $model->usersProfile->title;
$this->params['breadcrumbs'][] = ['label' => 'Организации', 'url' => ['index']];
$this->params['breadcrumbs'][] = $model->usersProfile->title;
?>
<div class="organization">
        <h4><?=$model->usersProfile->typeOrganization->value?> "<?=$model->usersProfile->title?>"</h4>
        <div class="left">
            <img src="<?=$model->usersProfile->getImage()->getUrl('120x120') ?>" alt="<?= Html::encode($this->title) ?>">
        </div>
        <div class="right">
            <?php foreach ($model->usersPhones as $key => $Phone) { ?>
            <div class="item">
                <i class="icon"></i>
                <span class="value"><?=$Phone->text;?></span>
            </div>
            <?php } ?>

            <?php foreach ($model->usersAddresses as $key => $Address) { ?>
                <div class="item" data-address="<?=$Address->geoText?>" data-address-name="<?=$Address->description?>" data-name="<?=$model->usersProfile->title?>">
                    <i class="icon"></i>
                    <span class="value"><?=$Address->text?></span>
                </div>
            <?php } ?>

            <div class="item">
                <i class="icon"></i>
                <span class="title">E-mail:</span>
                <span class="value"><a href="mailto:<?=$model->email;?>"><?=$model->email;?></a></span>
            </div>
            <div class="item status">
                <i class="icon"></i>
                <span class="title">Статус:</span>
                <span class="value marked"><?=$model->usersProfile->status->title;?></span>
            </div>
            <div class="item">
                <i class="icon"></i>
                <span class="title">Сайт:</span>
                <span class="value"><a href="http://<?=$model->usersProfile->url_www;?>"><?=$model->usersProfile->url_www;?></a></span>
            </div>
            <div class="item">
                <i class="icon"></i>
                <span class="title">Vk.com: </span>
                <a href="https://vk.com/<?=$model->usersProfile->url_vk;?>">
                    <span class="value"><?=$model->usersProfile->url_vk;?></span>
                </a>
            </div>
            <div class="item">
                <i class="icon"></i>
                <span class="title">Режим работы:</span>
                <span class="value"><?=$model->usersProfile->schedule;?></span>
            </div>
            <div class="item">
                <i class="icon"></i>
                <span class="title">Дата последнего обновления:</span>
                <span class="value"><?php
                    $date = new DateTime($model->updated_at);
                    echo $date->format('d.m.Y');
                    ?>
                    </span>
            </div>
        </div>
    <div class="clear"></div>
    <div id="map" style="width: 100%; height: 400px"></div>
    <div class="clear"></div>
</div>
<?php if($model->servicesDatas) {?>
<div class="search">
    <h3>Предложения от организации</h3>
    <div class="items">
      <?php
      foreach ($model->servicesDatas as $key => $data)
          echo $this->render('/services-data/_view',array(
              'data'=>$data,
          ));
      ?>
    </div>
</div>
<?php } else { ?>
  <p>Нет предложений от этой организации</p>
<?php }?>
    <h3>Отзывы</h3>

<script src="http://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
<script>
    function addPointToMap(map, item){
        var address = item.attr('data-address');
        var balloon = '';
        balloon += item.attr('data-name');
        balloon += '<br/>';
        balloon += item.attr('data-address-name');
        balloon += '<br/>';
        balloon += item.attr('data-address');
        var myGeocoder = ymaps.geocode(address);
        myGeocoder.then(
            function (res) {
                myGeoObject = new ymaps.GeoObject({
                        geometry: {
                            type: "Point",// тип геометрии - точка
                            coordinates: res.geoObjects.get(0).geometry.getCoordinates() // координаты точки
                        },
                        properties: {
                          balloonContentBody: balloon
                        }
                    });
                map.geoObjects.add(myGeoObject); // Размещение геообъекта на карте.
            },
            function (err) {
                cosole.log('Ошибка');
            }
        );
    }
    ymaps.ready(function () {
        var myMap = new ymaps.Map("map", {
              center: [56.009286, 92.872232],
              zoom: 13,
              controls: []
            });
        $(".item[data-address]").each(function(index, val) {
            addPointToMap(myMap,$(this));
        });
    });
</script>