backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use backend\models\LoginForm;
use common\models\ContactForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public $enableCsrfValidation = false; //Отключаем csfr валидацию, иначе не будет работать загрузка изображений и файлов

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
             'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionUploadImage()
    {
        $dir = 'images/upload/';
        $_FILES['file']['type'] = strtolower($_FILES['file']['type']);

        if ($_FILES['file']['type'] == 'image/png'
        || $_FILES['file']['type'] == 'image/jpg'
        || $_FILES['file']['type'] == 'image/gif'
        || $_FILES['file']['type'] == 'image/jpeg'
        || $_FILES['file']['type'] == 'image/pjpeg')
        {
            $file = md5(date('YmdHis')).'.'.pathinfo($_FILES['file']['name'], PATHINFO_EXTENSION);
            move_uploaded_file($_FILES['file']['tmp_name'], $dir.$file);
            $array = array(
                'filelink' => '/images/upload/'.$file
            );
            echo stripslashes(json_encode($array));
        }
    }

    public function actionUploadFile()
    {
        $dir = 'doc/';
        $file = md5(date('YmdHis')).'.'.pathinfo($_FILES['file']['name'], PATHINFO_EXTENSION);

        if (move_uploaded_file($_FILES['file']['tmp_name'], $dir.$file))
        {
             $array = array(
                'filelink' => '/doc/'.$file,
                'filename' => $_FILES['file']['name']
             );
             echo stripslashes(json_encode($array));
        }
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use frontend\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\widgets\ActiveForm;

use common\models\TypeOrganization;
use common\models\CodesPhones;
use common\models\UsersStatus;

use common\models\UsersAddress;
use common\models\UsersAddressRegion;
use common\models\UsersAddressCity;
use common\models\UsersAddressArea;
use common\models\UsersAddressStreet;

use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public $enableCsrfValidation = false;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'city'],
                'rules' => [
                    [
                        'actions' => ['signup', 'city'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            Yii::$app->session->setFlash('flashMessage', array('success', 'Вы успешно вошли.'));
            return $this->redirect(['users-profile']);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                return "Спасибо что свяались с нами. Ваше мнение очень важно для нас.";
            } else {
                return 'Произошла ошибка при отправке письма.';
            }
        } else {
            return $this->renderPartial('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    Yii::$app->session->setFlash('flashMessage', array('success', 'Вы успешно зарегистировались.'));
                    return $this->goHome();
                }
            }
        }

        $codesPhones = ArrayHelper::map(CodesPhones::find()->select('id, title')->where('is_visible=1')->all(), 'id', 'title');
        $typeOrganization = ArrayHelper::map(TypeOrganization::find()->select('id, value')->where('is_visible=1')->all(), 'id', 'value');
        $usersStatus = ArrayHelper::map(UsersStatus::find()->select('id, title')->where('is_visible=1')->all(), 'id', 'title');
        
        $addressRegion = ArrayHelper::map(UsersAddressRegion::find()->select('id, title')->where('is_visible=1')->all(), 'id', 'title');
        $addressCity = ArrayHelper::map(UsersAddressCity::find()->select('id, title')->where('is_visible=1')->all(), 'id', 'title');
        $addressArea = ArrayHelper::map(UsersAddressArea::find()->select('id, title')->where('is_visible=1')->all(), 'id', 'title');
        $addressStreet = ArrayHelper::map(UsersAddressStreet::find()->select('id, title')->where('is_visible=1')->all(), 'id', 'title');
        return $this->render('signup', [
            'model' => $model,
            'typeOrganization' =>  $typeOrganization,
            'codesPhones' =>  $codesPhones,
            'usersStatus' =>  $usersStatus,
            'addressRegion' =>  $addressRegion,
            'addressCity' =>  $addressCity,
            'addressArea' =>  $addressArea,
            'addressStreet' => $addressStreet
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }


    // add new address form
    public function actionField($index = false)
    {
        if($index == false){
            echo "";
            return;
        }
        $AddressRegion = ArrayHelper::map(UsersAddressRegion::find()->select('id, title')->where('is_visible=1')->all(), 'id', 'title');
        $model = new SignupForm();
        echo $this->renderPartial('_add_address_fields_ajax', array(
            'AddressRegion' =>  $AddressRegion,
            'model' => $model,
            'index' => $index,
        ));
    }


    // for dependet dropdown
    public function actionCity() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $cat_id = $parents[0];
                $out = ArrayHelper::map(UsersAddressCity::find()->select('id, title')->where(['is_visible' => 1 ,'id_region'=>$parents])->all(), 'id', 'title');
                echo Json::encode(['output' => $this->getDepDropData($out), 'selected'=>'']);
                return;
            }
        }
        echo Json::encode(['output'=>'1', 'selected'=>'1']);
    }
     
    public function actionArea() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $cat_id = $parents[0];
                $out = ArrayHelper::map(UsersAddressArea::find()->select('id, title')->where(['is_visible' => 1 ,'id_city'=>$parents])->all(), 'id', 'title');
                echo Json::encode(['output' => $this->getDepDropData($out), 'selected'=>'']);
                return;
            }
        }
        echo Json::encode(['output'=>'', 'selected'=>'']);
    }

    public function actionStreet() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $cat_id = $parents[0];
                $out = ArrayHelper::map(UsersAddressStreet::find()->select('id, title')->where(['is_visible' => 1 ,'id_area'=>$parents])->all(), 'id', 'title'); 
                echo Json::encode(['output' => $this->getDepDropData($out), 'selected'=>'']);
                return;
            }
        }
        echo Json::encode(['output'=>'', 'selected'=>'']);
    }
    private function getDepDropData($in){ // форматирует данные для DepDrop
        $out = array( );
        foreach ($in as $key => $value) {
            $out[] = ['id'=>$key, "name"=> $value];
        }
        return $out;
    }
}

frontend/views/site/_add_address_fields.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use kartik\widgets\DepDrop;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \frontend\models\SignupForm */
?>
    <div class="row address <?php if(!isset($model->address[$index]) && $index!=0) echo 'hide';?>">
        <div class="icon"></div>
        <div class="form-group">
            <label for="">Почтовый адрес:</label>
        </div>
        <?= $form->field($model, 'address['.$index.'][id_region]', ['template'=>'{input}{error}'])->dropDownList(
                $addressRegion,         
                [
                    'prompt'=>'Регион', 
                    'style'=> "width: 130px;", 
                    'id'=>'id_region'.$index, 
                    'class'=>"chosen",
                ]
            );
        ?>
       
        <?= $form->field($model, 'address['.$index.'][id_city]', ['template'=>'{input}{error}'])->widget(DepDrop::classname(), [
            'data' => $addressCity,
            'options'=>[
                'id'=>'id_city'.$index, 
                'placeholder'=>'Город', 
                'class'=>"chosen",
                'style'=> "width: 130px;"
            ],
            'pluginOptions'=>[
                'depends'=>['id_region'.$index],
                'placeholder'=>'Город',
                'url'=>Url::to(['/site/city'])
            ]
        ]); ?>

        <?= $form->field($model, 'address['.$index.'][id_area]', ['template'=>'{input}{error}'])->widget(DepDrop::classname(), [
            'data' => $addressArea,
            'options'=>[
                'id'=>'id_area'.$index, 
                'placeholder'=>'Исторический район', 
                'style'=> "width: 130px;", 
                'class'=>"chosen"
            ],
            'pluginOptions'=>[
                'depends'=>['id_city'.$index],
                'placeholder'=>'Исторический район',
                'url'=>Url::to(['/site/area'])
            ]
        ]); ?>

        <?= $form->field($model, 'address['.$index.'][id_street]', ['template'=>'{input}{error}'])->widget(DepDrop::classname(), [
            'data' => $addressStreet,
            'options'=>[
                'id'=>'id_street'.$index, 
                'placeholder'=>'Улица', 
                'style'=> "width: 130px;", 
                'class'=>"chosen"
            ],
            'pluginOptions'=>[
                'depends'=>['id_area'.$index],
                'placeholder'=>'Улица',
                'url'=>Url::to(['/site/street'])
            ]
        ]); ?>

        <?= $form->field($model, 'address['.$index.'][house]', ['template'=>'{input}{error}'])->textInput(['placeholder' => "Дом", 'style'=>"width: 80px;"]) ?>
        <?= $form->field($model, 'address['.$index.'][apartment]', ['template'=>'{input}{error}'])->textInput(['placeholder' => "Офис", 'style'=>"width: 80px;"]) ?>
        <button class="add">+</button>
    </div>
                   

frontend/views/site/_add_address_fields_ajax.php
<div class="row address">
        <div class="icon"></div>
        <div class="form-group">
            <label for="">Почтовый адрес:</label>
        </div>
        <div class="form-group field-signupform-address-<?=$index?>-id_region">
            <select id="id_region<?=$index?>" class="chosen depdrop" name="SignupForm[address][<?=$index?>][id_region]" style="width: 130px;">
            <option value="">Регион</option>
            <option value="4">Красноярский край</option>
            </select><div class="help-block"></div>
        </div>       
        <div class="form-group field-signupform-address-<?=$index?>-id_city">
            <select id="id_city<?=$index?>" class="chosen depdrop" name="SignupForm[address][<?=$index?>][id_city]" placeholder="Город" style="width: 130px;" data-plugin-name="depdrop" data-plugin-options="depdrop_3b54ebbf" disabled="disabled" depends="['id_region<?=$index?>']" url="/site/city">
                <option value="">Город</option>
            </select>
            <div class="help-block"></div>
        </div>
        <div class="form-group field-signupform-address-<?=$index?>-id_area">
            <select id="id_area<?=$index?>" class="chosen depdrop" name="SignupForm[address][<?=$index?>][id_area]" placeholder="Исторический район" style="width: 130px;" data-plugin-name="depdrop" data-plugin-options="depdrop_e1e39e90" disabled="disabled" depends="['id_region<?=$index?>']" url="/site/city">
            <option value="">Исторический район</option>
            </select><div class="help-block"></div>
        </div>
        <div class="form-group field-signupform-address-<?=$index?>-id_street">
            <select id="id_street<?=$index?>" class="chosen depdrop" name="SignupForm[address][<?=$index?>][id_street]" placeholder="Улица" style="width: 130px;" data-plugin-name="depdrop" data-plugin-options="depdrop_f689d298" disabled="disabled" depends="['id_region<?=$index?>']" url="/site/city">
                <option value="">Улица</option>
            </select>
            <div class="help-block"></div>
        </div>
        <div class="form-group field-signupform-address-<?=$index?>-home">
            <input type="text" id="signupform-address-<?=$index?>-home" class="form-control" name="SignupForm[address][<?=$index?>][home]" placeholder="Дом" style="width: 80px;"><div class="help-block"></div>
        </div>        
        <div class="form-group field-signupform-address-<?=$index?>-apartment">
            <input type="text" id="signupform-address-<?=$index?>-apartment" class="form-control" name="SignupForm[address][<?=$index?>][apartment]" placeholder="Офис" style="width: 80px;"><div class="help-block"></div>
        </div>        
        <button class="add">+</button>
</div>

frontend/views/site/about.php
<?php
use yii\helpers\Html;

/* @var $this yii\web\View */
$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\captcha\Captcha;
/*
/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \frontend\models\ContactForm */
/*
$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
*/
?>
<div class="site-contact">
    <p>
        Напишите нам, если у вас есть какие-либо пожелания или предложения. Спасибо.
    </p>
    <div>
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
                <div class="row">
                    <?= $form->field($model, 'body')->textArea(['rows' => 6, 'cols'=> 140]) ?>
                </div>
                 <div class="row inline">
                    <?= $form->field($model, 'subject', ['template'=>'{input}{error}'])->textInput(['placeholder' => $model->getAttributeLabel( 'subject' )]) ?>
                    <?= $form->field($model, 'name', ['template'=>'{input}{error}'])->textInput(['placeholder' => $model->getAttributeLabel( 'name' )]) ?>
                    <?= $form->field($model, 'email', ['template'=>'{input}{error}'])->textInput(['placeholder' => $model->getAttributeLabel( 'email' )]) ?>

                </div>
                <div class="row">
                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '{image}{input}',
                    ]) ?>
                </div>
                <div class="buttons">
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            <?php ActiveForm::end(); ?>
    </div>

</div>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php
/* @var $this yii\web\View */
$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

frontend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Вход в личный кабинет';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Вы можете зарегистрироваться в системе для получения пароля</p>
    <?= Html::a('Регистрация', ['site/signup'], ['class' => 'btn btn-primary']) ?>
    <p>Или войдите в систему, введя свой email и пароль.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                <?= $form->field($model, 'email') ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="clearfix"></div>
                <?= $form->field($model, 'rememberMe', ['template'=>'{input} {label} {error}'])->checkbox([],false) ?>
                <div class="clearfix"></div>
                <div class="form-group">
                    <?= Html::submitButton('Вход', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
                <div class="clearfix"></div>
                <div style="color:#999;margin:1em 0">
                    Если вы забыли пароль, вы можете <?= Html::a('Восстановить его', ['site/request-password-reset']) ?>.
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                <?= $form->field($model, 'email') ?>
                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
                <?= $form->field($model, 'password')->passwordInput() ?>
                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\captcha\Captcha;
use yii\helpers\Url;
use kartik\widgets\DepDrop;

/* @var $this yii\web\View */
/* @var $form yii\widgets\ActiveForm */
/* @var $model \frontend\models\SignupForm */

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
</div>
<div class="personal">
    <h1>Регистрация</h1>
    <div class="tabs">
        <menu class="menu">
            <li class="disabled">
                <a href="" rel="messages"><span>Сообщения</span></a>
            </li>
            <li class="active">
                <a href="" rel="information"><span>Общая информация</span></a>
            </li>
            <li class="disabled">
                <a href="" rel="services"><span>Мои услуги</span></a>
            </li>
            <li class="disabled">
                <a href="" rel="advanced"><span>Дополнительные возможности</span></a>
            </li>
            <li class="disabled">
                <a href="" rel="vip"><span>Vip-услуги</span></a>
            </li>
            <li class="disabled">
                <a href="" rel="packets"><span>Пакеты опций</span></a>
            </li>
        </menu>

        <div class="sections">
            <section class="tab" data-tab="information">
                <?= $this->render('signupForm', [
                    'model' => $model,
                    'typeOrganization' =>  $typeOrganization,
                    'codesPhones' =>  $codesPhones,
                    'usersStatus' =>  $usersStatus,
                    'addressRegion' =>  $addressRegion,
                    'addressCity' =>  $addressCity,
                    'addressArea' =>  $addressArea,
                    'addressStreet' =>  $addressStreet,
                ]); ?>
            </section>
        </div>
    </div>
</div>